# Generated by Django 5.2.1 on 2025-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
