# Generated by Django 5.2.1 on 2025-05-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_game_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
