# Generated by Django 5.2.1 on 2025-06-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_guess_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'ساده'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=10)),
            ],
        ),
    ]
