# Generated by Django 5.2.1 on 2025-06-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_wordbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbank',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=10),
        ),
        migrations.AlterField(
            model_name='wordbank',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
