# Generated by Django 5.2.1 on 2025-06-01 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_wordbank_difficulty_alter_wordbank_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='double_guess_player1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='double_guess_player2',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GameHintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_type', models.CharField(choices=[('reveal_letter', 'Reveal Random Letter'), ('letter_count', 'Letter Count'), ('double_guess', 'Double Guess')], max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints_used', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints_used', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
