# Generated by Django 5.2.1 on 2025-06-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_double_guess_player1_game_double_guess_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='double_guess_count_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='double_guess_count_player2',
            field=models.IntegerField(default=0),
        ),
    ]
